name: hledger-to-influxdb
version: 0.1.0.0
github: barrucadu/hledger-to-influxdb
license: MIT
author: Michael Walker
maintainer: mike@barrucadu.co.uk
copyright: 2018 Michael Walker

executables:
  hledger-to-influxdb-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -Wall
    dependencies:
    - base
