name: lint-journal
version: 0.1.0.0
github: barrucadu/hledger-scripts
license: MIT
author: Michael Walker
maintainer: mike@barrucadu.co.uk
copyright: 2018 Michael Walker

executables:
  lint-journal:
    main: Main.hs
    source-dirs: src
    ghc-options:
    - -Wall
    - -Werror
    dependencies:
    - base
    - containers
    - Decimal
    - hledger-lib
    - hledger-lib-extras
    - text
